<div class="col-sm-10 show-case-wrapper center-block relative">
    <div id="productShowCase" class="owl-carousel owl-theme">
      <div class="product-slide">
        <div class="col-sm-5 product-slide-left" > <a class="product-slide-img"> <img alt="img" src="<?php echo $this->getSkinUrl('images/product/24.jpg');?>" class="img-responsive"></a> </div>
        <div class="col-sm-7">
          <div class="product-slide-inner ">
            <h1 class="product-title"> Lorem ipsum dolor sit amet</h1>
            <h3 class="product-code">Product Code : DEN1098</h3>
            <div class="product-price"> <span class="price-sales"> $70</span> <span class="price-standard">$95</span> </div>
            <div class="details-description">
              <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum </p>
            </div>
            <a  title="Add to Cart" class="btn btn-stroke-dark" > <i class="glyphicon glyphicon-shopping-cart"></i> Add to Cart</a> </div>
        </div>
      </div>
      <div class="product-slide">
        <div class="col-sm-5 product-slide-left"> <a class="product-slide-img"> <img alt="img"  src="<?php echo $this->getSkinUrl('images/product/30.jpg');?>" class="img-responsive"></a> </div>
        <div class="col-sm-7 ">
          <div class="product-slide-inner ">
            <h1 class="product-title"> Lorem ipsum dolor sit amet</h1>
            <h3 class="product-code">Product Code : DEN1098</h3>
            <div class="product-price"> <span class="price-sales"> $70</span> <span class="price-standard">$95</span> </div>
            <div class="details-description">
              <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum </p>
            </div>
            <a  title="Add to Cart" class="btn btn-stroke-dark" > <i class="glyphicon glyphicon-shopping-cart"></i> Add to Cart</a> </div>
        </div>
      </div>
      <div class="product-slide">
        <div class="col-sm-5 product-slide-left"> <a class="product-slide-img"><img alt="img"  src="<?php echo $this->getSkinUrl('images/product/a2.jpg');?>" class="img-responsive"></a> </div>
        <div class="col-sm-7 ">
          <div class="product-slide-inner">
            <h1 class="product-title"> Lorem ipsum dolor sit amet</h1>
            <h3 class="product-code">Product Code : DEN1098</h3>
            <div class="product-price"> <span class="price-sales"> $70</span> <span class="price-standard">$95</span> </div>
            <div class="details-description">
              <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum Duis autem vel </p>
            </div>
            <a  title="Add to Cart" class="btn btn-stroke-dark" > <i class="glyphicon glyphicon-shopping-cart"></i> Add to Cart</a> </div>
        </div>
      </div>
      <div class="product-slide">
        <div class="col-sm-5 product-slide-left"> <a class="product-slide-img"><img alt="img"  src="<?php echo $this->getSkinUrl('images/product/5.jpg');?>" class="img-responsive"></a> </div>
        <div class="col-sm-7 ">
          <div class="product-slide-inner  ">
            <h1 class="product-title"> Lorem ipsum dolor sit amet</h1>
            <h3 class="product-code">Product Code : DEN1098</h3>
            <div class="product-price"> <span class="price-sales"> $70</span> <span class="price-standard">$95</span> </div>
            <div class="details-description">
              <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum</p>
            </div>
            <a  title="Add to Cart" class="btn btn-stroke-dark" > <i class="glyphicon glyphicon-shopping-cart"></i> Add to Cart</a> </div>
        </div>
      </div>
    </div>
    <!--/#productShowCase -->
    
    <div style="clear:both;"></div>
    <a id="ps-next" class="ps-nav"> <i class="fa fa-angle-right"></i> </a> <a id="ps-prev" class="ps-nav"> <i class="fa fa-angle-left"></i> </a> </div>
  <!--/.show-case-wrapper -->