<ul class="myAccountList row">
<li class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
  <div class="thumbnail equalheight"> <a title="<?php echo $this->__('Account Information');?>" href="<?php echo $this->getUrl();?>customer/account/edit/"><i class="fa fa-cog"></i> <?php echo $this->__('Account Information');?></a></div>
</li>
<li class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
  <div class="thumbnail equalheight"> <a title="<?php echo $this->__('Address Book');?>" href="<?php echo $this->getUrl();?>customer/address/"><i  class="fa fa-map-marker"></i> <?php echo $this->__('Address Book');?></a> </div>
</li>
<li class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
  <div class="thumbnail equalheight"> <a title="<?php echo $this->__('My Orders');?>" href="<?php echo $this->getUrl();?>sales/order/history/"><i class="fa fa-calendar"></i> <?php echo $this->__('My Orders');?> </a> </div>
</li>
<li class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
  <div class="thumbnail equalheight"> <a title="<?php echo $this->__('My Wishlist');?>" href="<?php echo $this->getUrl();?>wishlist/"><i class="fa fa-heart"></i> <?php echo $this->__('My Wishlist');?> </a> </div>
</li>
<li class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
  <div class="thumbnail equalheight"> 
<a title="<?php echo $this->__('Newsletter Subscriptions');?>" href="<?php echo $this->getUrl();?>newsletter/manage/"><i class="fa  fa-envelope"></i> <?php echo $this->__('Newsletter Subscriptions');?> </a> </div>
</li>

</ul>