<?php
$groupId = $this->getGroupId ();
$groupInfo = Mage::getModel('menupro/groupmenu')->load($groupId)->getData();
$MCPHTML = $MCPRHTML = "";
if ($this->helper('menupro')->isDevelopMode()) {
	if ($this->isGroupResponsive($groupInfo['responsive'])) {
		if ($groupInfo['responsive'] == "mcp-push-cover" || $groupInfo['responsive'] == "mcp-push-overlap") {
			$MCPRHTML = $this->getPushnewResponsiveHtml($groupId, $groupInfo['responsive']);
		} else {
			$MCPRHTML = $this->getPushResponsiveHtml($groupId, $groupInfo['responsive']);
		}
		$MCPHTML .= '<div class="visible-sm visible-xs">'.$MCPRHTML.'</div>';
		$MCPHTML .= '<div class="hidden-sm hidden-xs">'.$this->getMenuHtml($groupId).'</div>';
	} else {
		$MCPHTML = $this->getMenuHtml($groupId);
	}
} else {
	if ($this->isGroupResponsive($groupInfo['responsive'])) { 
		if ($groupInfo['responsive'] == "mcp-push-cover" || $groupInfo['responsive'] == "mcp-push-overlap") {
			$MCPRHTML = $this->getPushnewResponsiveHtml($groupId, $groupInfo['responsive']);
		} else {
			$MCPRHTML = $this->getPushResponsiveHtml($groupId, $groupInfo['responsive']);
		}
		$MCPHTML .= '<div class="visible-sm visible-xs">'.$MCPRHTML.'</div>';
		$MCPHTML .= '<div class="hidden-sm hidden-xs">'.$this->getStaticHtml($groupId).'</div>';
	} else {
		$MCPHTML = $this->getStaticHtml($groupId);
	}
}
?>
<div class="mcp-wrapper">
	<?php echo $MCPHTML; ?>
</div>
