<!--- navbar social icon || this part will be hidden on mobile version -->
<div class="nav navbar-nav navbar-right margin-top-10 hidden-xs">
<ul class="social-icon">
  <li> <a title="" class="fa fa-facebook tooltipHere" data-placement="bottom" data-toggle="tooltip" data-original-title="Facebook"  href="#"></a></li>
  <li> <a title="" class="fa fa-google-plus tooltipHere" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Google+"></a></li>
  <li> <a title="" class="fa fa-twitter tooltipHere" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Twitter"></a></li>
  <li> <a title="" class="fa fa-pinterest tooltipHere" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Pinterest"></a></li>
  <li> <a title="" class="fa fa-linkedin tooltipHere" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Linkedin"></a></li>
  <li> <a title="" class="fa fa-rss tooltipHere" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Feedburner"></a></li>
</ul>
</div><!--/.navbar-right || social icon end-->