<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @authors    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php
    $_productCollection=$this->getFeaturedProductCollection();
	$_productCollection->load(true);
    $_helper = $this->helper('catalog/output');
?>
<div class="morePost row featuredPostContainer style2 globalPaddingTop " >
    <h3 class="section-title style2 text-center"><span><?php echo $this->__('FEATURED PRODUCT');?></span></h3>
    <div class="container">
      <div class="row xsResponse EqualHeight">
		<?php if(!$_productCollection->count()): ?>
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php else: ?>
		<?php $_collectionSize = $_productCollection->count() ?>
		<?php $_columnCount = $this->getColumnCount(); ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
        <div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
          <div class="product">
			<?php if ($this->helper('wishlist')->isAllow()) : ?>
				<a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="add-fav tooltipHere" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Wishlist') ?>"  data-placement="left">
					<i class="glyphicon glyphicon-heart"></i>
				</a>
			<?php endif; ?>
				<div class="image"> 
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
						<?php $_imgSize = 240; ?>
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive"/>
					</a>
				<div class="promotion"> 
				<?php 
				$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
				$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
				$now = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
				if(($newFromDate < $now && $newFromDate != NULL) && ($newToDate > $now || $newToDate == "")){ ?>
				<span class="new-product"> <?php echo $this->__('NEW');?></span>
				<?php } ?>
				<?php 
				$_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());

				$_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());

				if ($_regularPrice != $_finalPrice):

				$getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);

				$finalpercentage = 100 - $getpercentage;

				echo '<span class="discount">'.number_format($finalpercentage, 0).'% OFF</span>' ;

				endif;

				?>			
				</div>
			  </div>
			  <div class="description">
				<h4><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image"><?php echo $this->escapeHtml($_product->getName()) ?></a></h4>
				<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
			  </div>
			  <div class="grid-description">
                <?php $string =  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
				echo preg_replace('/\s+?(\S+)?$/', '', substr($string, 0, 50));
				?>
              </div>
			  <div class="price"><?php echo $this->getPriceHtml($_product, true, '-new') ?></div>
			  <div class="action-control"> 
			  <?php if($_product->isSaleable()): ?>
				<a class="btn btn-primary" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"> <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i> <?php echo $this->__('Add to Cart') ?> </span> </a> 
				<?php else: ?>
					<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
				<?php endif; ?>
			  </div>
			</div>
        </div>
        <!--/.item--> 
		<?php endforeach ?>
		<?php endif; ?>
      </div>
      <!-- /.row -->
    </div>
    <!--/.container--> 
  </div>
<!--/.featuredPostContainer-->
