<div id="menu-group-1"><ul class='level0 menu-creator-pro menu-creator-pro-fade mcp-push-cover menu-creator-pro-cyan nav navbar-nav'><li class="  active  level0 col_0"><a title="<?php echo $this->__("Home") ?>" href="<?php echo $this->getMCPUrl() ?>" target="_self"><span><?php echo $this->__("Home") ?></span></a>
</li><li class="  mcpdropdown parent  level0 col_8"><a title="<?php echo $this->__("New Arrivals") ?>" href=" #" target="_self"> <span class="title"><?php echo $this->__("New Arrivals") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container8'><div class='grid-column grid-column3  '><ul class='level1'><li class=' '><a title="<?php echo $this->__("All New Products") ?>" href="<?php echo $this->getMCPBaseUrl() ?>new-products/all-new-products.html" target="_self"><span><?php echo $this->__("All New Products") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("New Tops") ?>" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-tops.html" target="_self"><span><?php echo $this->__("New Tops") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("New Shoes") ?>" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-shoes.html" target="_self"><span><?php echo $this->__("New Shoes") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("New T-Shirt") ?>" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-t-shirt.html" target="_self"><span><?php echo $this->__("New T-Shirt") ?></span></a>
</li></ul>

</div>
<div class='grid-column grid-column9  '><div class='static-block  '><ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

<ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

<ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

<ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

<ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

<ul class="col-lg-4 col-sm-4 col-md-4 col-xs-6">
<li class="no-margin productPopItem ">
<a href="#">
<img class="img-responsive" alt="img" src="http://placehold.it/240x240">
</a>
<a class="text-center productInfo alpha90" href="#">
Eodem modo typi
<br>
<span> $60 </span>
</a>

</li>
</ul>

</div>

</div>

</div>

</li><li class="  mcpdropdown parent  level0 col_1"><a title="<?php echo $this->__("Shop") ?>" href="<?php echo $this->getMCPBaseUrl() ?>shop.html" target="_self"data-hover='mcpdropdown'><span><?php echo $this->__("Shop") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container2'><ul><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Women Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection.html"><?php echo $this->__("Women Collection") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container2'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Kameez") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/kameez.html"><?php echo $this->__("Kameez") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Tops") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/tops.html"><?php echo $this->__("Tops") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Shoes") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/shoes.html"><?php echo $this->__("Shoes") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Party Dress") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/party-dress.html"><?php echo $this->__("Party Dress") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("T shirt") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/t-shirt.html"><?php echo $this->__("T shirt") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Women Fragrances") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/women-fragrances.html"><?php echo $this->__("Women Fragrances") ?></a>
</li></ul>

</div>

</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Men Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection.html"><?php echo $this->__("Men Collection") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container2'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Panjabi") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/panjabi.html"><?php echo $this->__("Panjabi") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Male Fragrances") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/male-fragrances.html"><?php echo $this->__("Male Fragrances") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Scarf") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/scarf.html"><?php echo $this->__("Scarf") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Sandal") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/sandal.html"><?php echo $this->__("Sandal") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Underwear") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/underwear.html"><?php echo $this->__("Underwear") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Winter Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/winter-collection.html"><?php echo $this->__("Winter Collection") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Men Accessories") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/men-accessories.html"><?php echo $this->__("Men Accessories") ?></a>
</li></ul>

</div>

</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Top Brands") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands.html"><?php echo $this->__("Top Brands") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container2'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Diesel") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/diesel.html"><?php echo $this->__("Diesel") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Farah") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/farah.html"><?php echo $this->__("Farah") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Lyle &amp; Scott") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/lyle-scott.html"><?php echo $this->__("Lyle &amp; Scott") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Pretty Green") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/pretty-green.html"><?php echo $this->__("Pretty Green") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Dunny") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/dunny.html"><?php echo $this->__("Dunny") ?></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li class="  mcpdropdown parent  level0 col_6"><a title="<?php echo $this->__("Pages") ?>" href=" #" target="_self"> <span class="title"><?php echo $this->__("Pages") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container6'><div class='grid-column grid-column4  '><a title="<?php echo $this->__("Home pages") ?>" class="nav-header" href="#" target="_self"><span class="title"><?php echo $this->__("Home pages") ?></span></a><ul class='level1'><li class=' '><a title="<?php echo $this->__("Home Version 1") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Home Version 1") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Home Version 2") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Home Version 2") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Home Version 3") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Home Version 3") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Home Version 4") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Home Version 4") ?></span></a>
</li></ul>

</div>
<div class='grid-column grid-column4  '><a title="<?php echo $this->__("Featured Pages") ?>" class="nav-header" href="#" target="_self"><span class="title"><?php echo $this->__("Featured Pages") ?></span></a><ul class='level1'><li class=' '><a title="<?php echo $this->__("Category") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Category") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Sub Category") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Sub Category") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Product Simple") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Product Simple") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Product Configurable") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Product Configurable") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Product Grouped ") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Product Grouped ") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Product Bundle") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Product Bundle") ?></span></a>
</li></ul>

</div>
<div class='grid-column grid-column4  '><a title="<?php echo $this->__("User Links") ?>" class="nav-header" href="#" target="_self"><span class="title"><?php echo $this->__("User Links") ?></span></a><ul class='level1'><li class=' '><a title="<?php echo $this->__("My Account") ?>" href="<?php echo $this->getMCPBaseUrl() ?>customer/account/" target="_self"><span><?php echo $this->__("My Account") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("My Cart") ?>" href="<?php echo $this->getMCPBaseUrl() ?>checkout/cart/" target="_self"><span><?php echo $this->__("My Cart") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("My Wishlist") ?>" href="<?php echo $this->getMCPBaseUrl() ?>wishlist/" target="_self"><span><?php echo $this->__("My Wishlist") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Login") ?>" href="<?php echo $this->getMCPBaseUrl() ?>customer/account/login/" target="_self"><span><?php echo $this->__("Login") ?></span></a>
</li></ul>

</div>

</div>

</li></ul>

</div>
