<ul><li/><a class="" title="<?php echo $this->__("Home") ?>" target="_self" href="<?php echo $this->getMCPUrl() ?>"><span><?php echo $this->__("Home") ?></span></a>
</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("New Arrivals") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("New Arrivals") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("New Arrivals") ?></h2><a class="mp-back" href="#">back</a><ul><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("tmpl") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("tmpl") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("tmpl") ?></h2><a class="mp-back" href="#">back</a><ul><li/><a class="" title="<?php echo $this->__("All New Products") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>new-products/all-new-products.html"><span><?php echo $this->__("All New Products") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("New Tops") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-tops.html"><span><?php echo $this->__("New Tops") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("New Shoes") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-shoes.html"><span><?php echo $this->__("New Shoes") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("New T-Shirt") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>new-products/new-t-shirt.html"><span><?php echo $this->__("New T-Shirt") ?></span></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("Shop") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>shop.html"><span><?php echo $this->__("Shop") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("Shop") ?></h2><a class="mp-back" href="#">back</a><ul><li class='autosub-item mb-icon mb-icon-arrow-left '><a title="<?php echo $this->__("Women Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection.html"><?php echo $this->__("Women Collection") ?></a><div class='mp-level'><h2>Women Collection</h2><a class="mp-back" href="#">back</a><ul><li class='level3 autosub-item '><a title="<?php echo $this->__("Kameez") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/kameez.html"><?php echo $this->__("Kameez") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Tops") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/tops.html"><?php echo $this->__("Tops") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Shoes") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/shoes.html"><?php echo $this->__("Shoes") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Party Dress") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/party-dress.html"><?php echo $this->__("Party Dress") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("T shirt") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/t-shirt.html"><?php echo $this->__("T shirt") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Women Fragrances") ?>" href="<?php echo $this->getMCPUrl()?>shop/women-collection/women-fragrances.html"><?php echo $this->__("Women Fragrances") ?></a>
</li></ul>

</div>

</li><li class='autosub-item mb-icon mb-icon-arrow-left '><a title="<?php echo $this->__("Men Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection.html"><?php echo $this->__("Men Collection") ?></a><div class='mp-level'><h2>Men Collection</h2><a class="mp-back" href="#">back</a><ul><li class='level3 autosub-item '><a title="<?php echo $this->__("Panjabi") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/panjabi.html"><?php echo $this->__("Panjabi") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Male Fragrances") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/male-fragrances.html"><?php echo $this->__("Male Fragrances") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Scarf") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/scarf.html"><?php echo $this->__("Scarf") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Sandal") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/sandal.html"><?php echo $this->__("Sandal") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Underwear") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/underwear.html"><?php echo $this->__("Underwear") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Winter Collection") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/winter-collection.html"><?php echo $this->__("Winter Collection") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Men Accessories") ?>" href="<?php echo $this->getMCPUrl()?>shop/men-collection/men-accessories.html"><?php echo $this->__("Men Accessories") ?></a>
</li></ul>

</div>

</li><li class='autosub-item mb-icon mb-icon-arrow-left '><a title="<?php echo $this->__("Top Brands") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands.html"><?php echo $this->__("Top Brands") ?></a><div class='mp-level'><h2>Top Brands</h2><a class="mp-back" href="#">back</a><ul><li class='level3 autosub-item '><a title="<?php echo $this->__("Diesel") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/diesel.html"><?php echo $this->__("Diesel") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Farah") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/farah.html"><?php echo $this->__("Farah") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Lyle &amp; Scott") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/lyle-scott.html"><?php echo $this->__("Lyle &amp; Scott") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Pretty Green") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/pretty-green.html"><?php echo $this->__("Pretty Green") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Dunny") ?>" href="<?php echo $this->getMCPUrl()?>shop/top-brands/dunny.html"><?php echo $this->__("Dunny") ?></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("Pages") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Pages") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("Pages") ?></h2><a class="mp-back" href="#">back</a><ul><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("Home pages") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Home pages") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("Home pages") ?></h2><a class="mp-back" href="#">back</a><ul><li/><a class="" title="<?php echo $this->__("Home Version 1") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Home Version 1") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Home Version 2") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Home Version 2") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Home Version 3") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Home Version 3") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Home Version 4") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Home Version 4") ?></span></a>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("Featured Pages") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Featured Pages") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("Featured Pages") ?></h2><a class="mp-back" href="#">back</a><ul><li/><a class="" title="<?php echo $this->__("Category") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Category") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Sub Category") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Sub Category") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Product Simple") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Product Simple") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Product Configurable") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Product Configurable") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Product Grouped ") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Product Grouped ") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Product Bundle") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Product Bundle") ?></span></a>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo $this->__("User Links") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("User Links") ?></span></a><div class="mp-level"><h2 class=""><?php echo $this->__("User Links") ?></h2><a class="mp-back" href="#">back</a><ul><li/><a class="" title="<?php echo $this->__("My Account") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>customer/account/"><span><?php echo $this->__("My Account") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("My Cart") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>checkout/cart/"><span><?php echo $this->__("My Cart") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("My Wishlist") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>wishlist/"><span><?php echo $this->__("My Wishlist") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Login") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>customer/account/login/"><span><?php echo $this->__("Login") ?></span></a>
</li></ul>

</div>

</li></ul>

</div>

</li></ul>
