<!--
Popup newsletter Subcribe
-->
<div class="modal fade hide" id="modalAds" role="dialog" >
	<div class="modal-dialog  modal-bg-1" style="background:url(<?php echo $this->getSkinUrl('images/modal-img-1.jpg');?>) right bottom no-repeat;">
		<div class="modal-body-content">
			<!--<a class="close" data-dismiss="modal">×</a>-->
			<div class="modal-body">
				<div class="col-lg-6 col-sm-8 col-xs-8">
				<h3>enter your <br>email to  receive</h3>
				<p class="discountLg">10% OFF </p>
				<p>We invite you to subscribe to our newsletter and receive 10% discount.
				</p>
				<div class="clearfx"> 
				<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail-popup" class="newsletter">
				<input type="text" name="email" id="newsletter2" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" placeholder="Enter your email" /> 
				<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button btn  bg-gray subscribe-btn dismiss"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
				</form>
				<script type="text/javascript">
				//<![CDATA[
					var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail-popup');
				//]]>
				</script>
				</div>
				<p> <a class="link shoplink dismiss" data-dismiss="modal">No, thanks. <small>(Don't show me this again)</small></a></p>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
 // this script required for subscribe modal
jQuery(document).ready(function() {
 // full load
 if (jQuery.cookie('modal') == null) {
		jQuery('#modalAds').modal('show');
		jQuery('#modalAds').removeClass('hide');
     }
	jQuery('.dismiss').click(function(){
		jQuery.cookie('modal', 1);
	});
});

</script>