<div class="panel-heading" >
	<div class="row">
		<div class="col-lg-10"><h3 class="panel-title">BEFORE MAIN CONTENT</h3><small>Extra blocks for slideshow, big banner ( home page blocks only)</small></div>
		<div class="col-lg-2 pull-right">
			<div class="btn-group pull-right">
				<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("Save") ?></button>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="before-main-content">
	<div class="col-lg-12 block-change" >
		<div class="block1" data-block="block1">
			<div class="row">
				<div class="col-lg-9">Block 1</div>
				<div class="col-lg-3 text-right">
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full Width (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full Width (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">Grid (12)</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a> 				
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="block2" data-block="block2">
			<div class="row">
				<div class="col-lg-9">Block 2</div>
				<div class="col-lg-3 text-right">
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full Width (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full Width (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">Grid (12)</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a> 				
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="block3" data-block="block3">
			<div class="row">
				<div class="col-lg-9">Block 3</div>
				<div class="col-lg-3 text-right">
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full Width (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full Width (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">Grid (12)</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a> 				
			</div>
		</div>
	</div>
</div>