<div class="panel-heading">
	<div class="row">
		<div class="col-lg-9"><h3 class="panel-title">HEADER  </h3><small>Logo, Site Search, Phone Numbers, Main Menu, User Account Links, Benefits, Dropdown Cart ..etc</small></div>
				<div class="col-lg-3 pull-right">
			<div  class="btn-toolbar pull-right" role="toolbar">
				<div class="btn-group">
					<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Width <span class="caret"></span>
						</a>
					<ul class="dropdown-menu box-width" role="menu">
					<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
					<li><a class="box-width-type" rel="t2-section-full">Full Width (padding 15px)</a></li>
					<li><a class="box-width-type" rel="t2-section-full no-padding">Full Width (no padding)</a></li>
					</ul>
				</div>
				<div class="btn-group">
					<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("Save") ?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="t2header">
	<div class="col-lg-12 block-change">
		<div class="header-top"  data-block="header-top"> 
			<div class="row">
				<div class="col-lg-10"><span>Header Top</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">Grid (12)</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a> 				
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="header-mid"  data-block="header-mid">
			<div class="row">
				<div class="col-lg-10"><span>Header Middle</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>Grid (12) </p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a>
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a>
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="header-bottom"  data-block="header-bottom">
			<div class="row">
				<div class="col-lg-10"><span>Header Bottom</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__("Add Inner Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>Grid (12) </p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Settings"  ><i class="glyphicon glyphicon-cog"></i></a>
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Column"  ><i class="glyphicon glyphicon-remove-circle"></i></a>
			</div>
		</div>
	</div>
</div>