<div class="panel-heading">
	<div class="row">
		<div class="col-lg-9"><h3 class="panel-title">MAIN CONTENT (Dynamic content)</h3><small>Just allow to update grid layout of sidebars and main content</small></div>
		<div class="col-lg-3 pull-right">
			<div  class="btn-toolbar pull-right" role="toolbar">
				<div class="btn-group">
					<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
						Main Content Width <span class="caret"></span>
					</a>
					<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full (no padding)</a></li>
					</ul>
				</div>				
				<div class="btn-group">
					<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("SAVE") ?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="maincontent">
	<div class="col-lg-12">
		<div class="row">
			<div> 
				<div class="col-lg-12 border-dash">
					<p>
						<span class="column-num">Breadcrumb</span>				
					</p>
				</div>
			</div>
			<div data-block="left" class="left" style="clear: both; position: relative; display: block; padding-top: 20px;"> 
				<div class="col-lg-3 border-dash">
					<p>
						<span class="column-num">3 col</span>				
					</p>
					<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				</div>
			</div>
			<div class="col-lg-6"  data-block="message">
				<div class="col-lg-12 border-dash">
				<p>6 col| <small>Message notification</small>
				</p>
				</div>
				<div class="col-lg-12 border-dash" data-block="content">
				<p>6 col| <small>Main Content</small>
				</p>
				</div>
				
			</div>
			<div class="right"  data-block="right"  style="position: relative;"> 
				<div class="col-lg-3 border-dash">
						<span class="column-num">3 col</span>				
					</p>
					<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				</div>
			</div>
		</div>
	</div>
</div>